-- +goose Up
ALTER TABLE schedule_combo
  ADD COLUMN IF NOT EXISTS combo_index INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS instructor_name TEXT NOT NULL DEFAULT 'Staff',
  ADD COLUMN IF NOT EXISTS building TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS room_number TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'Unknown',
  ADD COLUMN IF NOT EXISTS is_in_person BOOLEAN NOT NULL DEFAULT FALSE;

-- +goose Down
ALTER TABLE schedule_combo
  DROP COLUMN IF EXISTS is_in_person,
  DROP COLUMN IF EXISTS mode,
  DROP COLUMN IF EXISTS room_number,
  DROP COLUMN IF EXISTS building,
  DROP COLUMN IF EXISTS instructor_name,
  DROP COLUMN IF EXISTS combo_index;
