root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "yaml", "yml", "toml", "env"]
exclude_dir = ["tmp", "vendor", "tests"]
delay = 200
stop_on_error = true
send_interrupt = true
kill_delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
