// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: antirequisite.sql

package db

import (
	"context"
)

const addProgramAntirequisite = `-- name: AddProgramAntirequisite :exec
INSERT INTO program_antirequisites (program_id, course_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProgramAntirequisiteParams struct {
	ProgramID int64
	CourseID  int64
}

func (q *Queries) AddProgramAntirequisite(ctx context.Context, arg AddProgramAntirequisiteParams) error {
	_, err := q.db.Exec(ctx, addProgramAntirequisite, arg.ProgramID, arg.CourseID)
	return err
}

const getProgramAntirequisites = `-- name: GetProgramAntirequisites :many
SELECT pa.course_id, c.code, c.name
FROM program_antirequisites pa
JOIN course c ON c.id = pa.course_id
WHERE pa.program_id = $1
ORDER BY c.code
`

type GetProgramAntirequisitesRow struct {
	CourseID int64
	Code     string
	Name     string
}

func (q *Queries) GetProgramAntirequisites(ctx context.Context, programID int64) ([]GetProgramAntirequisitesRow, error) {
	rows, err := q.db.Query(ctx, getProgramAntirequisites, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProgramAntirequisitesRow
	for rows.Next() {
		var i GetProgramAntirequisitesRow
		if err := rows.Scan(&i.CourseID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestrictionsForProgramCourses = `-- name: GetRestrictionsForProgramCourses :many
SELECT c.id, c.code, c.restrictions
FROM course c
JOIN program_courses pc ON pc.course_id = c.id
WHERE pc.program_id = $1
  AND c.restrictions != ''
`

type GetRestrictionsForProgramCoursesRow struct {
	ID           int64
	Code         string
	Restrictions string
}

func (q *Queries) GetRestrictionsForProgramCourses(ctx context.Context, programID int64) ([]GetRestrictionsForProgramCoursesRow, error) {
	rows, err := q.db.Query(ctx, getRestrictionsForProgramCourses, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRestrictionsForProgramCoursesRow
	for rows.Next() {
		var i GetRestrictionsForProgramCoursesRow
		if err := rows.Scan(&i.ID, &i.Code, &i.Restrictions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProgramAntirequisite = `-- name: RemoveProgramAntirequisite :exec
DELETE FROM program_antirequisites
WHERE program_id = $1 AND course_id = $2
`

type RemoveProgramAntirequisiteParams struct {
	ProgramID int64
	CourseID  int64
}

func (q *Queries) RemoveProgramAntirequisite(ctx context.Context, arg RemoveProgramAntirequisiteParams) error {
	_, err := q.db.Exec(ctx, removeProgramAntirequisite, arg.ProgramID, arg.CourseID)
	return err
}
