// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const addUserAvoidedCourse = `-- name: AddUserAvoidedCourse :exec
INSERT INTO user_detail_avoided_courses (user_id, course_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserAvoidedCourseParams struct {
	UserID   uuid.UUID
	CourseID int64
}

func (q *Queries) AddUserAvoidedCourse(ctx context.Context, arg AddUserAvoidedCourseParams) error {
	_, err := q.db.Exec(ctx, addUserAvoidedCourse, arg.UserID, arg.CourseID)
	return err
}

const addUserCompletedCourse = `-- name: AddUserCompletedCourse :exec
INSERT INTO user_detail_completed_courses (user_id, course_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserCompletedCourseParams struct {
	UserID   uuid.UUID
	CourseID int64
}

func (q *Queries) AddUserCompletedCourse(ctx context.Context, arg AddUserCompletedCourseParams) error {
	_, err := q.db.Exec(ctx, addUserCompletedCourse, arg.UserID, arg.CourseID)
	return err
}

const createEmbedding = `-- name: CreateEmbedding :exec
UPDATE course
SET embedding = $2
WHERE code = $1
`

type CreateEmbeddingParams struct {
	Code      string
	Embedding pgvector.Vector
}

func (q *Queries) CreateEmbedding(ctx context.Context, arg CreateEmbeddingParams) error {
	_, err := q.db.Exec(ctx, createEmbedding, arg.Code, arg.Embedding)
	return err
}

const getAllCourseCodes = `-- name: GetAllCourseCodes :one
SELECT array_agg(code)::varchar[]
FROM course
`

func (q *Queries) GetAllCourseCodes(ctx context.Context) ([]string, error) {
	row := q.db.QueryRow(ctx, getAllCourseCodes)
	var column_1 []string
	err := row.Scan(&column_1)
	return column_1, err
}

const getCourseByCode = `-- name: GetCourseByCode :one
SELECT id, code, name, description, restrictions, prerequisites, units, term, level_number
FROM course
WHERE code = $1
LIMIT 1
`

type GetCourseByCodeRow struct {
	ID            int64
	Code          string
	Name          string
	Description   string
	Restrictions  string
	Prerequisites []string
	Units         int32
	Term          string
	LevelNumber   pgtype.Int4
}

func (q *Queries) GetCourseByCode(ctx context.Context, code string) (GetCourseByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCourseByCode, code)
	var i GetCourseByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Restrictions,
		&i.Prerequisites,
		&i.Units,
		&i.Term,
		&i.LevelNumber,
	)
	return i, err
}

const getCourseIDByCode = `-- name: GetCourseIDByCode :one
SELECT id
FROM course
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetCourseIDByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, getCourseIDByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCoursesByVectorSearch = `-- name: GetCoursesByVectorSearch :many
SELECT 
    c.id, c.code, c.name, c.description, c.restrictions, c.prerequisites, c.units, c.term, c.level_number,
    c.embedding <=> $1::vector AS distance
FROM course c
LEFT JOIN program_courses pc 
    ON pc.course_id = c.id 
    AND pc.program_id = $2::bigint
WHERE
    ($3::int  IS NULL OR c.level_number = $3)
    AND ($4::text  IS NULL OR c.term = $4)
    AND ($5::text  IS NULL OR c.code ILIKE $5 || '%')
    AND NOT EXISTS (
        SELECT 1 FROM user_detail_avoided_courses uac
        WHERE uac.course_id = c.id AND uac.user_id = $6::uuid
    )
    AND ($2::bigint IS NULL OR c.id NOT IN (
        SELECT course_id FROM program_antirequisites WHERE program_id = $2::bigint
    ))
ORDER BY
    CASE WHEN $1::vector IS NULL 
        THEN (CASE WHEN pc.program_id IS NOT NULL THEN 0 ELSE 1 END)
        ELSE (c.embedding <=> $1::vector) - (CASE WHEN pc.program_id IS NOT NULL THEN 0.3 ELSE 0 END)
    END ASC
LIMIT $7::int
`

type GetCoursesByVectorSearchParams struct {
	Embedding     pgvector.Vector
	UserProgramID pgtype.Int8
	Level         pgtype.Int4
	Term          pgtype.Text
	Code          pgtype.Text
	UserID        uuid.UUID
	Limit         int32
}

type GetCoursesByVectorSearchRow struct {
	ID            int64
	Code          string
	Name          string
	Description   string
	Restrictions  string
	Prerequisites []string
	Units         int32
	Term          string
	LevelNumber   pgtype.Int4
	Distance      interface{}
}

func (q *Queries) GetCoursesByVectorSearch(ctx context.Context, arg GetCoursesByVectorSearchParams) ([]GetCoursesByVectorSearchRow, error) {
	rows, err := q.db.Query(ctx, getCoursesByVectorSearch,
		arg.Embedding,
		arg.UserProgramID,
		arg.Level,
		arg.Term,
		arg.Code,
		arg.UserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesByVectorSearchRow
	for rows.Next() {
		var i GetCoursesByVectorSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Restrictions,
			&i.Prerequisites,
			&i.Units,
			&i.Term,
			&i.LevelNumber,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchedulesForCourse = `-- name: GetSchedulesForCourse :many
SELECT sc.id, sc.combo_index, sc.day, sc.start_time, sc.end_time, sc.type, sc.section, sc.instructor_name, sc.building, sc.room_number, sc.mode, sc.is_in_person, sc.course_id, t.avg_difficulty, t.avg_rating
FROM schedule_combo AS sc
JOIN teacher t
  ON t.name = sc.instructor_name
WHERE sc.course_id = $1
ORDER BY sc.section
`

type GetSchedulesForCourseRow struct {
	ID             int32
	ComboIndex     int32
	Day            string
	StartTime      pgtype.Time
	EndTime        pgtype.Time
	Type           string
	Section        string
	InstructorName string
	Building       string
	RoomNumber     string
	Mode           string
	IsInPerson     bool
	CourseID       int64
	AvgDifficulty  pgtype.Numeric
	AvgRating      pgtype.Numeric
}

func (q *Queries) GetSchedulesForCourse(ctx context.Context, courseID int64) ([]GetSchedulesForCourseRow, error) {
	rows, err := q.db.Query(ctx, getSchedulesForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSchedulesForCourseRow
	for rows.Next() {
		var i GetSchedulesForCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.ComboIndex,
			&i.Day,
			&i.StartTime,
			&i.EndTime,
			&i.Type,
			&i.Section,
			&i.InstructorName,
			&i.Building,
			&i.RoomNumber,
			&i.Mode,
			&i.IsInPerson,
			&i.CourseID,
			&i.AvgDifficulty,
			&i.AvgRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
