// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const addUserAvoidedCourse = `-- name: AddUserAvoidedCourse :exec
INSERT INTO user_detail_avoided_courses (user_id, course_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserAvoidedCourseParams struct {
	UserID   uuid.UUID
	CourseID int64
}

func (q *Queries) AddUserAvoidedCourse(ctx context.Context, arg AddUserAvoidedCourseParams) error {
	_, err := q.db.Exec(ctx, addUserAvoidedCourse, arg.UserID, arg.CourseID)
	return err
}

const addUserCompletedCourse = `-- name: AddUserCompletedCourse :exec
INSERT INTO user_detail_completed_courses (user_id, course_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserCompletedCourseParams struct {
	UserID   uuid.UUID
	CourseID int64
}

func (q *Queries) AddUserCompletedCourse(ctx context.Context, arg AddUserCompletedCourseParams) error {
	_, err := q.db.Exec(ctx, addUserCompletedCourse, arg.UserID, arg.CourseID)
	return err
}

const createEmbedding = `-- name: CreateEmbedding :exec
UPDATE course
SET embedding = $2
WHERE code = $1
`

type CreateEmbeddingParams struct {
	Code      string
	Embedding pgvector.Vector
}

func (q *Queries) CreateEmbedding(ctx context.Context, arg CreateEmbeddingParams) error {
	_, err := q.db.Exec(ctx, createEmbedding, arg.Code, arg.Embedding)
	return err
}

const getAllCourseCodes = `-- name: GetAllCourseCodes :one
SELECT array_agg(code)::varchar[]
FROM course
`

func (q *Queries) GetAllCourseCodes(ctx context.Context) ([]string, error) {
	row := q.db.QueryRow(ctx, getAllCourseCodes)
	var column_1 []string
	err := row.Scan(&column_1)
	return column_1, err
}

const getCourseByCode = `-- name: GetCourseByCode :one
SELECT id, code, name, description, restrictions, prerequisites, units, level_number
FROM course
WHERE code = $1
LIMIT 1
`

type GetCourseByCodeRow struct {
	ID            int64
	Code          string
	Name          string
	Description   string
	Restrictions  string
	Prerequisites []string
	Units         int32
	LevelNumber   pgtype.Int4
}

func (q *Queries) GetCourseByCode(ctx context.Context, code string) (GetCourseByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCourseByCode, code)
	var i GetCourseByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Restrictions,
		&i.Prerequisites,
		&i.Units,
		&i.LevelNumber,
	)
	return i, err
}

const getCourseIDByCode = `-- name: GetCourseIDByCode :one
SELECT id
FROM course
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetCourseIDByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, getCourseIDByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCourseSectionsByTerm = `-- name: GetCourseSectionsByTerm :many
SELECT 
  sm.id,
  s.name AS section,
  s.type,
  s.term,
  s.mode,
  s.is_in_person,
  sm.days AS day,
  sm.start_time,
  sm.end_time,
  sm.building,
  sm.room,
  COALESCE(STRING_AGG(t.name, ', '), 'Staff') AS instructor_name,
  COALESCE(AVG(t.avg_difficulty), 0) AS avg_difficulty,
  COALESCE(AVG(t.avg_rating), 0) AS avg_rating
FROM section AS s
JOIN section_meeting AS sm ON sm.section_id = s.id
LEFT JOIN section_teachers AS st ON st.section_id = s.id
LEFT JOIN teacher AS t ON t.id = st.teacher_id
JOIN course AS c ON c.id = s.course_id
WHERE c.code = $1::text AND s.term = $2::text
GROUP BY sm.id, s.id
ORDER BY s.name
`

type GetCourseSectionsByTermParams struct {
	Code string
	Term string
}

type GetCourseSectionsByTermRow struct {
	ID             int32
	Section        string
	Type           string
	Term           string
	Mode           string
	IsInPerson     bool
	Day            string
	StartTime      pgtype.Time
	EndTime        pgtype.Time
	Building       string
	Room           string
	InstructorName interface{}
	AvgDifficulty  interface{}
	AvgRating      interface{}
}

func (q *Queries) GetCourseSectionsByTerm(ctx context.Context, arg GetCourseSectionsByTermParams) ([]GetCourseSectionsByTermRow, error) {
	rows, err := q.db.Query(ctx, getCourseSectionsByTerm, arg.Code, arg.Term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseSectionsByTermRow
	for rows.Next() {
		var i GetCourseSectionsByTermRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.Type,
			&i.Term,
			&i.Mode,
			&i.IsInPerson,
			&i.Day,
			&i.StartTime,
			&i.EndTime,
			&i.Building,
			&i.Room,
			&i.InstructorName,
			&i.AvgDifficulty,
			&i.AvgRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesByVectorSearch = `-- name: GetCoursesByVectorSearch :many
SELECT 
    c.id, c.code, c.name, c.description, c.restrictions, c.prerequisites, c.units, c.level_number,
    CASE WHEN $1::boolean = false 
        THEN NULL 
        ELSE c.embedding <=> $2::vector 
    END AS distance
FROM course c
LEFT JOIN program_courses pc 
    ON pc.course_id = c.id 
    AND pc.program_id = $3::bigint
WHERE
    ($4::int  IS NULL OR c.level_number = $4)
    AND ($5::text IS NULL OR EXISTS (
        SELECT 1 FROM section sec WHERE sec.course_id = c.id AND sec.term = $5
    ))
    AND ($6::text  IS NULL OR c.code ILIKE $6 || '%')
    AND NOT EXISTS (
        SELECT 1 FROM user_detail_avoided_courses uac
        WHERE uac.course_id = c.id AND uac.user_id = $7::uuid
    )
    AND ($3::bigint IS NULL OR c.id NOT IN (
        SELECT course_id FROM program_antirequisites WHERE program_id = $3::bigint
    ))
ORDER BY
    CASE WHEN $1::boolean = false 
        THEN (CASE WHEN pc.program_id IS NOT NULL THEN 0 ELSE 1 END)
        ELSE (c.embedding <=> $2::vector) - (CASE WHEN pc.program_id IS NOT NULL THEN 0.3 ELSE 0 END)
    END ASC
LIMIT $8::int
`

type GetCoursesByVectorSearchParams struct {
	HasEmbedding  bool
	Embedding     pgvector_go.Vector
	UserProgramID pgtype.Int8
	Level         pgtype.Int4
	Term          pgtype.Text
	Code          pgtype.Text
	UserID        uuid.UUID
	Limit         int32
}

type GetCoursesByVectorSearchRow struct {
	ID            int64
	Code          string
	Name          string
	Description   string
	Restrictions  string
	Prerequisites []string
	Units         int32
	LevelNumber   pgtype.Int4
	Distance      interface{}
}

func (q *Queries) GetCoursesByVectorSearch(ctx context.Context, arg GetCoursesByVectorSearchParams) ([]GetCoursesByVectorSearchRow, error) {
	rows, err := q.db.Query(ctx, getCoursesByVectorSearch,
		arg.HasEmbedding,
		arg.Embedding,
		arg.UserProgramID,
		arg.Level,
		arg.Term,
		arg.Code,
		arg.UserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoursesByVectorSearchRow
	for rows.Next() {
		var i GetCoursesByVectorSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Restrictions,
			&i.Prerequisites,
			&i.Units,
			&i.LevelNumber,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchedulesForCourse = `-- name: GetSchedulesForCourse :many
SELECT 
  sm.id,
  s.name AS section,
  s.type,
  s.term,
  s.mode,
  s.is_in_person,
  sm.days AS day,
  sm.start_time,
  sm.end_time,
  sm.building,
  sm.room,
  COALESCE(STRING_AGG(t.name, ', '), 'Staff') AS instructor_name,
  COALESCE(AVG(t.avg_difficulty), 0) AS avg_difficulty,
  COALESCE(AVG(t.avg_rating), 0) AS avg_rating
FROM section AS s
JOIN section_meeting AS sm ON sm.section_id = s.id
LEFT JOIN section_teachers AS st ON st.section_id = s.id
LEFT JOIN teacher AS t ON t.id = st.teacher_id
WHERE s.course_id = $1
GROUP BY sm.id, s.id
ORDER BY s.name
`

type GetSchedulesForCourseRow struct {
	ID             int32
	Section        string
	Type           string
	Term           string
	Mode           string
	IsInPerson     bool
	Day            string
	StartTime      pgtype.Time
	EndTime        pgtype.Time
	Building       string
	Room           string
	InstructorName interface{}
	AvgDifficulty  interface{}
	AvgRating      interface{}
}

func (q *Queries) GetSchedulesForCourse(ctx context.Context, courseID int64) ([]GetSchedulesForCourseRow, error) {
	rows, err := q.db.Query(ctx, getSchedulesForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSchedulesForCourseRow
	for rows.Next() {
		var i GetSchedulesForCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.Type,
			&i.Term,
			&i.Mode,
			&i.IsInPerson,
			&i.Day,
			&i.StartTime,
			&i.EndTime,
			&i.Building,
			&i.Room,
			&i.InstructorName,
			&i.AvgDifficulty,
			&i.AvgRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
