// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addUserAvoidedCourse = `-- name: AddUserAvoidedCourse :exec
INSERT INTO user_detail_avoided_courses (user_id, course_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserAvoidedCourseParams struct {
	UserID   uuid.UUID
	CourseID int64
}

func (q *Queries) AddUserAvoidedCourse(ctx context.Context, arg AddUserAvoidedCourseParams) error {
	_, err := q.db.Exec(ctx, addUserAvoidedCourse, arg.UserID, arg.CourseID)
	return err
}

const addUserCompletedCourse = `-- name: AddUserCompletedCourse :exec
INSERT INTO user_detail_completed_courses (user_id, course_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserCompletedCourseParams struct {
	UserID   uuid.UUID
	CourseID int64
}

func (q *Queries) AddUserCompletedCourse(ctx context.Context, arg AddUserCompletedCourseParams) error {
	_, err := q.db.Exec(ctx, addUserCompletedCourse, arg.UserID, arg.CourseID)
	return err
}

const getCourseIDByCode = `-- name: GetCourseIDByCode :one
SELECT id
FROM course
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetCourseIDByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, getCourseIDByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}
