// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Course struct {
	ID            int64
	Code          string
	Name          string
	Description   string
	Restrictions  string
	Prerequisites []string
	Units         int32
	LevelNumber   pgtype.Int4
	Embedding     pgvector.Vector
}

type CourseTeacher struct {
	CourseID  int64
	TeacherID int32
}

type Plan struct {
	ID        uuid.UUID
	Title     string
	Term      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	UserID    uuid.UUID
}

type PlanCourse struct {
	ID       uuid.UUID
	PlanID   uuid.UUID
	CourseID int64
}

type PlanSection struct {
	PlanCourseID uuid.UUID
	SectionID    int32
}

type Program struct {
	ID                  int64
	Name                string
	SourceUrl           pgtype.Text
	RequirementCodes    []string
	RequirementsByLevel []byte
}

type ProgramAntirequisite struct {
	ProgramID int64
	CourseID  int64
}

type ProgramCourse struct {
	ProgramID int64
	CourseID  int64
}

type ProgramRequirementGroup struct {
	ID                 int64
	ProgramID          int64
	LevelLabel         string
	LevelTotalUnits    pgtype.Int4
	GroupUnits         pgtype.Text
	SortOrder          int32
	ChooseOne          bool
	RequirementLevelID pgtype.Int8
	GroupName          pgtype.Text
}

type ProgramRequirementItem struct {
	ID                 int64
	RequirementGroupID int64
	RequirementText    string
	CourseCode         pgtype.Text
	CourseID           pgtype.Int8
	IsCourse           bool
	SortOrder          int32
}

type ProgramRequirementLevel struct {
	ID          int64
	ProgramID   int64
	LevelNumber pgtype.Text
	SortOrder   int32
}

type ScrapeRun struct {
	ID                uuid.UUID
	Source            string
	Status            string
	Metadata          []byte
	ErrorMessage      pgtype.Text
	CourseCount       int32
	ProgramCount      int32
	TeacherCount      int32
	ScheduleTermCount int32
	StartedAt         pgtype.Timestamptz
	StagedAt          pgtype.Timestamptz
	PromotedAt        pgtype.Timestamptz
	FailedAt          pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Section struct {
	ID         int32
	CourseID   int64
	Name       string
	Type       string
	Term       string
	Mode       string
	IsInPerson bool
}

type SectionMeeting struct {
	ID        int32
	SectionID int32
	Days      string
	StartTime pgtype.Time
	EndTime   pgtype.Time
	Building  string
	Room      string
}

type SectionReference struct {
	ParentSectionID int32
	ChildSectionID  int32
}

type SectionTeacher struct {
	SectionID int32
	TeacherID int32
}

type StagingCourse struct {
	RunID      uuid.UUID
	CourseCode string
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
}

type StagingProgram struct {
	RunID       uuid.UUID
	ProgramName string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
}

type StagingSchedule struct {
	RunID      uuid.UUID
	Term       string
	CourseCode string
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
}

type StagingTeacher struct {
	RunID     uuid.UUID
	RmpID     string
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

type Teacher struct {
	ID            int32
	Name          string
	AvgRating     pgtype.Numeric
	AvgDifficulty pgtype.Numeric
	Department    string
	RmpID         string
	NumRatings    int32
}

type TeacherProgram struct {
	TeacherID int32
	ProgramID int64
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserDetail struct {
	UserID           uuid.UUID
	Year             int16
	JobInfo          string
	FuturePlans      string
	ProfessorQuality int16
	TeachingStyle    int16
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Completed        pgtype.Bool
	WakeUpTime       pgtype.Time
	Bedtime          pgtype.Time
	ProgramID        pgtype.Int8
	Lat              pgtype.Float8
	Lng              pgtype.Float8
}

type UserDetailAvoidedCourse struct {
	UserID   uuid.UUID
	CourseID int64
}

type UserDetailCompletedCourse struct {
	UserID   uuid.UUID
	CourseID int64
}
