// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserDetail struct {
	ID               int64
	UserID           int64
	Program          string
	Year             int16
	CompletedCourses []string
	JobInfo          string
	HomeAddress      string
	FuturePlans      string
	ProfessorQuality int16
	TeachingStyle    int16
	AvoidedCourses   []string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Completed        pgtype.Bool
	WakeUpTime       pgtype.Time
	Bedtime          pgtype.Time
}
