// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID            int64
	Code          string
	Name          string
	Description   string
	Restrictions  string
	Prerequisites []string
	Units         int32
	Term          string
	LevelNumber   pgtype.Int4
}

type CourseTeacher struct {
	CourseID  int64
	TeacherID int32
}

type Program struct {
	ID                  int64
	Name                string
	SourceUrl           pgtype.Text
	RequirementCodes    []string
	RequirementsByLevel []byte
}

type ProgramCourse struct {
	ProgramID int64
	CourseID  int64
}

type ProgramRequirementGroup struct {
	ID                 int64
	ProgramID          int64
	LevelLabel         string
	LevelTotalUnits    pgtype.Int4
	GroupUnits         pgtype.Text
	SortOrder          int32
	ChooseOne          bool
	RequirementLevelID pgtype.Int8
	GroupName          pgtype.Text
}

type ProgramRequirementItem struct {
	ID                 int64
	RequirementGroupID int64
	RequirementText    string
	CourseCode         pgtype.Text
	CourseID           pgtype.Int8
	IsCourse           bool
	SortOrder          int32
}

type ProgramRequirementLevel struct {
	ID          int64
	ProgramID   int64
	LevelNumber pgtype.Text
	SortOrder   int32
}

type ScheduleCombo struct {
	ID             int32
	ComboIndex     int32
	Day            string
	StartTime      pgtype.Time
	EndTime        pgtype.Time
	Type           string
	Section        string
	InstructorName string
	Building       string
	RoomNumber     string
	Mode           string
	IsInPerson     bool
	CourseID       int64
}

type Teacher struct {
	ID            int32
	Name          string
	AvgRating     pgtype.Numeric
	AvgDifficulty pgtype.Numeric
	Department    string
	RmpID         string
	NumRatings    int32
}

type TeacherProgram struct {
	TeacherID int32
	ProgramID int64
}

type User struct {
	ID        uuid.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserDetail struct {
	UserID           uuid.UUID
	Year             int16
	JobInfo          string
	HomeAddress      string
	FuturePlans      string
	ProfessorQuality int16
	TeachingStyle    int16
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Completed        pgtype.Bool
	WakeUpTime       pgtype.Time
	Bedtime          pgtype.Time
	ProgramID        pgtype.Int8
}

type UserDetailAvoidedCourse struct {
	UserID   uuid.UUID
	CourseID int64
}

type UserDetailCompletedCourse struct {
	UserID   uuid.UUID
	CourseID int64
}
