// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plan (title, term, user_id) VALUES ($1, $2, $3)
RETURNING id
`

type CreatePlanParams struct {
	Title  string
	Term   string
	UserID uuid.UUID
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPlan, arg.Title, arg.Term, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPlanInfo = `-- name: GetPlanInfo :one
SELECT 
  p.id, p.title, p.term, p.created_at, p.updated_at, p.user_id,
  (
    SELECT COALESCE(
      JSON_AGG(
        JSON_BUILD_OBJECT(
          'id', pc.id,
          'course_id', c.id,
          'code', c.code,
          'name', c.name,
          'description', c.description,
          'restrictions', c.restrictions,
          'prerequisites', c.prerequisites,
          'units', c.units,
          'types', (
            SELECT COALESCE(JSON_AGG(t.type), '[]'::json)
            FROM (
              SELECT DISTINCT type
              FROM section s_inner
              WHERE s_inner.course_id = c.id
            ) t
          ),
          'teachers', (
            SELECT COALESCE(
              JSON_AGG(
                JSON_BUILD_OBJECT(
                  'id', t.id,
                  'name', t.name,
                  'avg_rating', t.avg_rating,
                  'avg_difficulty', t.avg_difficulty,
                  'department', t.department,
                  'rmp_id', t.rmp_id,
                  'num_ratings', t.num_ratings
                )
              ), 
              '[]'::json
            )
            FROM (
              SELECT teacher.id, teacher.name, teacher.avg_rating, teacher.avg_difficulty, teacher.department, teacher.rmp_id, teacher.num_ratings
              FROM course_teachers ct
              JOIN teacher ON teacher.id = ct.teacher_id
              WHERE ct.course_id = c.id
            ) t
          ),
          'sections', (
            SELECT COALESCE(
              JSON_AGG(
                JSON_BUILD_OBJECT(
                  'id', s.id,
                  'name', s.name,
                  'type', s.type,
                  'term', s.term,
                  'mode', s.mode,
                  'is_in_person', s.is_in_person,
                  'meetings', (
                    SELECT COALESCE(
                      JSON_AGG(
                        JSON_BUILD_OBJECT(
                          'id', sm.id,
                          'days', sm.days,
                          'start_time', sm.start_time,
                          'end_time', sm.end_time,
                          'building', sm.building,
                          'room', sm.room
                        )
                      ), 
                      '[]'::json
                    )
                    FROM section_meeting sm
                    WHERE sm.section_id = s.id
                  ),
                  'teachers', (
                    SELECT COALESCE(
                      JSON_AGG(
                        JSON_BUILD_OBJECT(
                          'id', teacher.id,
                          'name', teacher.name,
                          'avg_rating', teacher.avg_rating,
                          'avg_difficulty', teacher.avg_difficulty,
                          'department', teacher.department,
                          'rmp_id', teacher.rmp_id,
                          'num_ratings', teacher.num_ratings
                        )
                      ), 
                      '[]'::json
                    )
                    FROM section_teachers st
                    JOIN teacher ON teacher.id = st.teacher_id
                    WHERE st.section_id = s.id
                  )
                )
              ),
              '[]'::json
            )
            FROM plan_section ps
            JOIN section s ON s.id = ps.section_id
            WHERE ps.plan_course_id = pc.id
          )
        )
      ), 
      '[]'::json
    )
    FROM plan_course pc
    JOIN course c ON c.id = pc.course_id
    WHERE pc.plan_id = p.id
  )::json AS courses
FROM plan p
WHERE p.id = $1::UUID AND p.user_id = $2::UUID
`

type GetPlanInfoParams struct {
	PlanID uuid.UUID
	UserID uuid.UUID
}

type GetPlanInfoRow struct {
	ID        uuid.UUID
	Title     string
	Term      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	UserID    uuid.UUID
	Courses   []byte
}

func (q *Queries) GetPlanInfo(ctx context.Context, arg GetPlanInfoParams) (GetPlanInfoRow, error) {
	row := q.db.QueryRow(ctx, getPlanInfo, arg.PlanID, arg.UserID)
	var i GetPlanInfoRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Term,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Courses,
	)
	return i, err
}

const getPlans = `-- name: GetPlans :many
SELECT p.id, p.title, p.term, p.created_at, p.updated_at, p.user_id, COUNT(pc.course_id) as course_count
FROM plan p
LEFT JOIN plan_course pc ON p.id = pc.plan_id
WHERE p.user_id = $1
GROUP BY p.id
`

type GetPlansRow struct {
	ID          uuid.UUID
	Title       string
	Term        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	UserID      uuid.UUID
	CourseCount int64
}

func (q *Queries) GetPlans(ctx context.Context, userID uuid.UUID) ([]GetPlansRow, error) {
	rows, err := q.db.Query(ctx, getPlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlansRow
	for rows.Next() {
		var i GetPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Term,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.CourseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
