// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plan (title, term, user_id) VALUES ($1, $2, $3)
RETURNING id
`

type CreatePlanParams struct {
	Title  string
	Term   string
	UserID uuid.UUID
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPlan, arg.Title, arg.Term, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPlans = `-- name: GetPlans :many
SELECT p.id, p.title, p.term, p.created_at, p.updated_at, p.user_id, COUNT(ps.course_id) as course_count
FROM plan p
LEFT JOIN plan_section ps ON p.id = ps.plan_id
WHERE p.user_id = $1
GROUP BY p.id
`

type GetPlansRow struct {
	ID          uuid.UUID
	Title       string
	Term        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	UserID      uuid.UUID
	CourseCount int64
}

func (q *Queries) GetPlans(ctx context.Context, userID uuid.UUID) ([]GetPlansRow, error) {
	rows, err := q.db.Query(ctx, getPlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlansRow
	for rows.Next() {
		var i GetPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Term,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.CourseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
