// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: program.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProgramIDByName = `-- name: GetProgramIDByName :one
SELECT id
FROM program
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetProgramIDByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, getProgramIDByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getProgramRequirements = `-- name: GetProgramRequirements :one
WITH requirement_hierarchy AS (
  SELECT
    prl.program_id,
    jsonb_build_object(
      'levels',
      jsonb_agg(
        jsonb_build_object(
          'levelNumber', prl.level_number,
          'index', prl.sort_order,
          'groups', COALESCE(
            (
              SELECT jsonb_agg(
                jsonb_build_object(
                  'name', prg.group_name,
                  'units', prg.group_units,
                  'chooseOne', prg.choose_one,
                  'requirements', COALESCE(
                    (
                      SELECT jsonb_agg(
                        jsonb_build_object(
                          'type', CASE WHEN pri.is_course THEN 'course' ELSE 'text' END,
                          'text', pri.requirement_text,
                          'courseCode', pri.course_code
                        )
                        ORDER BY pri.sort_order, pri.id
                      )
                      FROM program_requirement_item pri
                      WHERE pri.requirement_group_id = prg.id
                    ),
                    '[]'::jsonb
                  )
                )
                ORDER BY prg.sort_order, prg.id
              )
              FROM program_requirement_group prg
              WHERE prg.requirement_level_id = prl.id
            ),
            '[]'::jsonb
          )
        )
        ORDER BY prl.sort_order, prl.id
      )
    ) AS requirements
  FROM program_requirement_level prl
  GROUP BY prl.program_id
)
SELECT
    p.id as program_id,
    p.name as program_name,
    COALESCE(rh.requirements, p.requirements_by_level, '{"levels":[]}'::jsonb) as requirement_groups
FROM program p
LEFT JOIN requirement_hierarchy rh ON rh.program_id = p.id
WHERE p.name = $1
`

type GetProgramRequirementsRow struct {
	ProgramID         int64
	ProgramName       string
	RequirementGroups []byte
}

// a very very disgusting query but it works
func (q *Queries) GetProgramRequirements(ctx context.Context, name string) (GetProgramRequirementsRow, error) {
	row := q.db.QueryRow(ctx, getProgramRequirements, name)
	var i GetProgramRequirementsRow
	err := row.Scan(&i.ProgramID, &i.ProgramName, &i.RequirementGroups)
	return i, err
}

const getUserProgramID = `-- name: GetUserProgramID :one
SELECT ud.program_id as codes
FROM user_details AS ud
WHERE ud.user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProgramID(ctx context.Context, id uuid.UUID) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getUserProgramID, id)
	var codes pgtype.Int8
	err := row.Scan(&codes)
	return codes, err
}

const getUserProgramName = `-- name: GetUserProgramName :one
SELECT p.name
FROM user_details AS ud
JOIN program p 
  ON p.id = ud.program_id
WHERE ud.user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProgramName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserProgramName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUserProgramRequirementCodes = `-- name: GetUserProgramRequirementCodes :many
SELECT DISTINCT ucode::text
FROM user_details AS ud
JOIN program p
  ON p.id = ud.program_id
CROSS JOIN unnest(p.requirement_codes) AS ucode
WHERE ud.user_id = $1
`

func (q *Queries) GetUserProgramRequirementCodes(ctx context.Context, id uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserProgramRequirementCodes, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ucode string
		if err := rows.Scan(&ucode); err != nil {
			return nil, err
		}
		items = append(items, ucode)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProgramRequirementCodesAvailableInTerm = `-- name: GetUserProgramRequirementCodesAvailableInTerm :many
SELECT DISTINCT ucode::text
FROM user_details AS ud
JOIN program p
  ON p.id = ud.program_id
CROSS JOIN unnest(p.requirement_codes) AS ucode
JOIN course c ON c.code = ucode::text
JOIN section s ON s.course_id = c.id
WHERE ud.user_id = $1 AND s.term = $2
`

type GetUserProgramRequirementCodesAvailableInTermParams struct {
	ID   uuid.UUID
	Term string
}

func (q *Queries) GetUserProgramRequirementCodesAvailableInTerm(ctx context.Context, arg GetUserProgramRequirementCodesAvailableInTermParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserProgramRequirementCodesAvailableInTerm, arg.ID, arg.Term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ucode string
		if err := rows.Scan(&ucode); err != nil {
			return nil, err
		}
		items = append(items, ucode)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProgramRequirements = `-- name: GetUserProgramRequirements :one
SELECT p.requirement_codes as codes
FROM user_details AS ud
JOIN program p
  ON p.id = ud.program_id
WHERE ud.user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProgramRequirements(ctx context.Context, id uuid.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getUserProgramRequirements, id)
	var codes []string
	err := row.Scan(&codes)
	return codes, err
}
