// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email)
VALUES ($1)
RETURNING id, email, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserDetails = `-- name: CreateUserDetails :one
INSERT INTO user_details (
    wake_up_time,
    bedtime,
    user_id,
    program,
    year,
    completed_courses,
    job_info,
    home_address,
    future_plans,
    professor_quality,
    teaching_style,
    avoided_courses,
    completed
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, true)
RETURNING id
`

type CreateUserDetailsParams struct {
	WakeUpTime       pgtype.Time
	Bedtime          pgtype.Time
	UserID           int64
	Program          string
	Year             int16
	CompletedCourses []string
	JobInfo          string
	HomeAddress      string
	FuturePlans      string
	ProfessorQuality int16
	TeachingStyle    int16
	AvoidedCourses   []string
}

func (q *Queries) CreateUserDetails(ctx context.Context, arg CreateUserDetailsParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUserDetails,
		arg.WakeUpTime,
		arg.Bedtime,
		arg.UserID,
		arg.Program,
		arg.Year,
		arg.CompletedCourses,
		arg.JobInfo,
		arg.HomeAddress,
		arg.FuturePlans,
		arg.ProfessorQuality,
		arg.TeachingStyle,
		arg.AvoidedCourses,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasCompletedOnboarding = `-- name: HasCompletedOnboarding :one
SELECT EXISTS (SELECT user_id FROM user_details WHERE user_id=$1)
`

func (q *Queries) HasCompletedOnboarding(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasCompletedOnboarding, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
