// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scrape_ingest.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearScrapeRunStagedCourses = `-- name: ClearScrapeRunStagedCourses :exec
DELETE FROM staging_courses WHERE run_id = $1
`

func (q *Queries) ClearScrapeRunStagedCourses(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearScrapeRunStagedCourses, runID)
	return err
}

const clearScrapeRunStagedPrograms = `-- name: ClearScrapeRunStagedPrograms :exec
DELETE FROM staging_programs WHERE run_id = $1
`

func (q *Queries) ClearScrapeRunStagedPrograms(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearScrapeRunStagedPrograms, runID)
	return err
}

const clearScrapeRunStagedSchedules = `-- name: ClearScrapeRunStagedSchedules :exec
DELETE FROM staging_schedules WHERE run_id = $1
`

func (q *Queries) ClearScrapeRunStagedSchedules(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearScrapeRunStagedSchedules, runID)
	return err
}

const clearScrapeRunStagedTeachers = `-- name: ClearScrapeRunStagedTeachers :exec
DELETE FROM staging_teachers WHERE run_id = $1
`

func (q *Queries) ClearScrapeRunStagedTeachers(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearScrapeRunStagedTeachers, runID)
	return err
}

const createScrapeRun = `-- name: CreateScrapeRun :one
INSERT INTO scrape_runs (source, metadata)
VALUES ($1, $2)
RETURNING id, source, status, metadata, error_message, course_count, program_count, teacher_count, schedule_term_count, started_at, staged_at, promoted_at, failed_at, created_at, updated_at
`

type CreateScrapeRunParams struct {
	Source   string
	Metadata []byte
}

func (q *Queries) CreateScrapeRun(ctx context.Context, arg CreateScrapeRunParams) (ScrapeRun, error) {
	row := q.db.QueryRow(ctx, createScrapeRun, arg.Source, arg.Metadata)
	var i ScrapeRun
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Status,
		&i.Metadata,
		&i.ErrorMessage,
		&i.CourseCount,
		&i.ProgramCount,
		&i.TeacherCount,
		&i.ScheduleTermCount,
		&i.StartedAt,
		&i.StagedAt,
		&i.PromotedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScrapeSection = `-- name: CreateScrapeSection :one
INSERT INTO section (course_id, name, type, term, mode, is_in_person)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateScrapeSectionParams struct {
	CourseID   int64
	Name       string
	Type       string
	Term       string
	Mode       string
	IsInPerson bool
}

func (q *Queries) CreateScrapeSection(ctx context.Context, arg CreateScrapeSectionParams) (int32, error) {
	row := q.db.QueryRow(ctx, createScrapeSection,
		arg.CourseID,
		arg.Name,
		arg.Type,
		arg.Term,
		arg.Mode,
		arg.IsInPerson,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createScrapeSectionMeeting = `-- name: CreateScrapeSectionMeeting :exec
INSERT INTO section_meeting (section_id, days, start_time, end_time, building, room)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateScrapeSectionMeetingParams struct {
	SectionID int32
	Days      string
	StartTime pgtype.Time
	EndTime   pgtype.Time
	Building  string
	Room      string
}

func (q *Queries) CreateScrapeSectionMeeting(ctx context.Context, arg CreateScrapeSectionMeetingParams) error {
	_, err := q.db.Exec(ctx, createScrapeSectionMeeting,
		arg.SectionID,
		arg.Days,
		arg.StartTime,
		arg.EndTime,
		arg.Building,
		arg.Room,
	)
	return err
}

const deleteScrapeProgramCourses = `-- name: DeleteScrapeProgramCourses :exec
DELETE FROM program_courses
WHERE program_id = $1
`

func (q *Queries) DeleteScrapeProgramCourses(ctx context.Context, programID int64) error {
	_, err := q.db.Exec(ctx, deleteScrapeProgramCourses, programID)
	return err
}

const deleteScrapeSectionsForTerms = `-- name: DeleteScrapeSectionsForTerms :exec
DELETE FROM section
WHERE term = ANY($1::text[])
`

func (q *Queries) DeleteScrapeSectionsForTerms(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteScrapeSectionsForTerms, dollar_1)
	return err
}

const getScrapeRun = `-- name: GetScrapeRun :one
SELECT id, source, status, metadata, error_message, course_count, program_count, teacher_count, schedule_term_count, started_at, staged_at, promoted_at, failed_at, created_at, updated_at
FROM scrape_runs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetScrapeRun(ctx context.Context, id uuid.UUID) (ScrapeRun, error) {
	row := q.db.QueryRow(ctx, getScrapeRun, id)
	var i ScrapeRun
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Status,
		&i.Metadata,
		&i.ErrorMessage,
		&i.CourseCount,
		&i.ProgramCount,
		&i.TeacherCount,
		&i.ScheduleTermCount,
		&i.StartedAt,
		&i.StagedAt,
		&i.PromotedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertScrapeCourseTeacher = `-- name: InsertScrapeCourseTeacher :exec
INSERT INTO course_teachers (course_id, teacher_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertScrapeCourseTeacherParams struct {
	CourseID  int64
	TeacherID int32
}

func (q *Queries) InsertScrapeCourseTeacher(ctx context.Context, arg InsertScrapeCourseTeacherParams) error {
	_, err := q.db.Exec(ctx, insertScrapeCourseTeacher, arg.CourseID, arg.TeacherID)
	return err
}

const insertScrapeProgramCourse = `-- name: InsertScrapeProgramCourse :exec
INSERT INTO program_courses (program_id, course_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertScrapeProgramCourseParams struct {
	ProgramID int64
	CourseID  int64
}

func (q *Queries) InsertScrapeProgramCourse(ctx context.Context, arg InsertScrapeProgramCourseParams) error {
	_, err := q.db.Exec(ctx, insertScrapeProgramCourse, arg.ProgramID, arg.CourseID)
	return err
}

const insertScrapeSectionReference = `-- name: InsertScrapeSectionReference :exec
INSERT INTO section_references (parent_section_id, child_section_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertScrapeSectionReferenceParams struct {
	ParentSectionID int32
	ChildSectionID  int32
}

func (q *Queries) InsertScrapeSectionReference(ctx context.Context, arg InsertScrapeSectionReferenceParams) error {
	_, err := q.db.Exec(ctx, insertScrapeSectionReference, arg.ParentSectionID, arg.ChildSectionID)
	return err
}

const insertScrapeSectionTeacher = `-- name: InsertScrapeSectionTeacher :exec
INSERT INTO section_teachers (section_id, teacher_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertScrapeSectionTeacherParams struct {
	SectionID int32
	TeacherID int32
}

func (q *Queries) InsertScrapeSectionTeacher(ctx context.Context, arg InsertScrapeSectionTeacherParams) error {
	_, err := q.db.Exec(ctx, insertScrapeSectionTeacher, arg.SectionID, arg.TeacherID)
	return err
}

const insertScrapeTeacherProgramLinks = `-- name: InsertScrapeTeacherProgramLinks :exec
INSERT INTO teacher_programs (teacher_id, program_id)
SELECT DISTINCT ct.teacher_id, pc.program_id
FROM course_teachers ct
JOIN program_courses pc ON pc.course_id = ct.course_id
ON CONFLICT DO NOTHING
`

func (q *Queries) InsertScrapeTeacherProgramLinks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, insertScrapeTeacherProgramLinks)
	return err
}

const listScrapeCourseIDs = `-- name: ListScrapeCourseIDs :many
SELECT code, id
FROM course
ORDER BY code
`

type ListScrapeCourseIDsRow struct {
	Code string
	ID   int64
}

func (q *Queries) ListScrapeCourseIDs(ctx context.Context) ([]ListScrapeCourseIDsRow, error) {
	rows, err := q.db.Query(ctx, listScrapeCourseIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScrapeCourseIDsRow
	for rows.Next() {
		var i ListScrapeCourseIDsRow
		if err := rows.Scan(&i.Code, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScrapeTeacherIDsByName = `-- name: ListScrapeTeacherIDsByName :many
SELECT name, id
FROM teacher
ORDER BY name ASC, num_ratings ASC
`

type ListScrapeTeacherIDsByNameRow struct {
	Name string
	ID   int32
}

func (q *Queries) ListScrapeTeacherIDsByName(ctx context.Context) ([]ListScrapeTeacherIDsByNameRow, error) {
	rows, err := q.db.Query(ctx, listScrapeTeacherIDsByName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScrapeTeacherIDsByNameRow
	for rows.Next() {
		var i ListScrapeTeacherIDsByNameRow
		if err := rows.Scan(&i.Name, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedCoursePayloads = `-- name: ListStagedCoursePayloads :many
SELECT payload
FROM staging_courses
WHERE run_id = $1
ORDER BY course_code
`

func (q *Queries) ListStagedCoursePayloads(ctx context.Context, runID uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listStagedCoursePayloads, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var payload []byte
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedProgramPayloads = `-- name: ListStagedProgramPayloads :many
SELECT payload
FROM staging_programs
WHERE run_id = $1
ORDER BY program_name
`

func (q *Queries) ListStagedProgramPayloads(ctx context.Context, runID uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listStagedProgramPayloads, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var payload []byte
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedSchedulePayloads = `-- name: ListStagedSchedulePayloads :many
SELECT payload
FROM staging_schedules
WHERE run_id = $1
ORDER BY term, course_code
`

func (q *Queries) ListStagedSchedulePayloads(ctx context.Context, runID uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listStagedSchedulePayloads, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var payload []byte
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedScheduleTerms = `-- name: ListStagedScheduleTerms :many
SELECT DISTINCT term
FROM staging_schedules
WHERE run_id = $1
ORDER BY term
`

func (q *Queries) ListStagedScheduleTerms(ctx context.Context, runID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listStagedScheduleTerms, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var term string
		if err := rows.Scan(&term); err != nil {
			return nil, err
		}
		items = append(items, term)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedTeacherPayloads = `-- name: ListStagedTeacherPayloads :many
SELECT payload
FROM staging_teachers
WHERE run_id = $1
ORDER BY rmp_id
`

func (q *Queries) ListStagedTeacherPayloads(ctx context.Context, runID uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listStagedTeacherPayloads, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var payload []byte
		if err := rows.Scan(&payload); err != nil {
			return nil, err
		}
		items = append(items, payload)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScrapeRunFailed = `-- name: MarkScrapeRunFailed :exec
UPDATE scrape_runs
SET status = 'failed',
    failed_at = NOW(),
    updated_at = NOW(),
    error_message = $2
WHERE id = $1
`

type MarkScrapeRunFailedParams struct {
	ID           uuid.UUID
	ErrorMessage pgtype.Text
}

func (q *Queries) MarkScrapeRunFailed(ctx context.Context, arg MarkScrapeRunFailedParams) error {
	_, err := q.db.Exec(ctx, markScrapeRunFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markScrapeRunPromoting = `-- name: MarkScrapeRunPromoting :exec
UPDATE scrape_runs
SET status = 'promoting',
    updated_at = NOW(),
    error_message = NULL
WHERE id = $1
`

func (q *Queries) MarkScrapeRunPromoting(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markScrapeRunPromoting, id)
	return err
}

const markScrapeRunStaged = `-- name: MarkScrapeRunStaged :exec
UPDATE scrape_runs
SET status = 'staged',
    course_count = $2,
    program_count = $3,
    teacher_count = $4,
    schedule_term_count = $5,
    staged_at = NOW(),
    updated_at = NOW(),
    error_message = NULL
WHERE id = $1
`

type MarkScrapeRunStagedParams struct {
	ID                uuid.UUID
	CourseCount       int32
	ProgramCount      int32
	TeacherCount      int32
	ScheduleTermCount int32
}

func (q *Queries) MarkScrapeRunStaged(ctx context.Context, arg MarkScrapeRunStagedParams) error {
	_, err := q.db.Exec(ctx, markScrapeRunStaged,
		arg.ID,
		arg.CourseCount,
		arg.ProgramCount,
		arg.TeacherCount,
		arg.ScheduleTermCount,
	)
	return err
}

const markScrapeRunSucceeded = `-- name: MarkScrapeRunSucceeded :exec
UPDATE scrape_runs
SET status = 'succeeded',
    promoted_at = NOW(),
    updated_at = NOW(),
    error_message = NULL
WHERE id = $1
`

func (q *Queries) MarkScrapeRunSucceeded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markScrapeRunSucceeded, id)
	return err
}

const stageCoursePayload = `-- name: StageCoursePayload :exec
INSERT INTO staging_courses (run_id, course_code, payload)
VALUES ($1, $2, $3)
ON CONFLICT (run_id, course_code) DO UPDATE SET
  payload = EXCLUDED.payload
`

type StageCoursePayloadParams struct {
	RunID      uuid.UUID
	CourseCode string
	Payload    []byte
}

func (q *Queries) StageCoursePayload(ctx context.Context, arg StageCoursePayloadParams) error {
	_, err := q.db.Exec(ctx, stageCoursePayload, arg.RunID, arg.CourseCode, arg.Payload)
	return err
}

const stageProgramPayload = `-- name: StageProgramPayload :exec
INSERT INTO staging_programs (run_id, program_name, payload)
VALUES ($1, $2, $3)
ON CONFLICT (run_id, program_name) DO UPDATE SET
  payload = EXCLUDED.payload
`

type StageProgramPayloadParams struct {
	RunID       uuid.UUID
	ProgramName string
	Payload     []byte
}

func (q *Queries) StageProgramPayload(ctx context.Context, arg StageProgramPayloadParams) error {
	_, err := q.db.Exec(ctx, stageProgramPayload, arg.RunID, arg.ProgramName, arg.Payload)
	return err
}

const stageSchedulePayload = `-- name: StageSchedulePayload :exec
INSERT INTO staging_schedules (run_id, term, course_code, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (run_id, term, course_code) DO UPDATE SET
  payload = EXCLUDED.payload
`

type StageSchedulePayloadParams struct {
	RunID      uuid.UUID
	Term       string
	CourseCode string
	Payload    []byte
}

func (q *Queries) StageSchedulePayload(ctx context.Context, arg StageSchedulePayloadParams) error {
	_, err := q.db.Exec(ctx, stageSchedulePayload,
		arg.RunID,
		arg.Term,
		arg.CourseCode,
		arg.Payload,
	)
	return err
}

const stageTeacherPayload = `-- name: StageTeacherPayload :exec
INSERT INTO staging_teachers (run_id, rmp_id, payload)
VALUES ($1, $2, $3)
ON CONFLICT (run_id, rmp_id) DO UPDATE SET
  payload = EXCLUDED.payload
`

type StageTeacherPayloadParams struct {
	RunID   uuid.UUID
	RmpID   string
	Payload []byte
}

func (q *Queries) StageTeacherPayload(ctx context.Context, arg StageTeacherPayloadParams) error {
	_, err := q.db.Exec(ctx, stageTeacherPayload, arg.RunID, arg.RmpID, arg.Payload)
	return err
}

const upsertScrapeCourse = `-- name: UpsertScrapeCourse :exec
INSERT INTO course (code, name, description, restrictions, prerequisites, units, level_number)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  restrictions = EXCLUDED.restrictions,
  prerequisites = EXCLUDED.prerequisites,
  units = EXCLUDED.units,
  level_number = EXCLUDED.level_number
`

type UpsertScrapeCourseParams struct {
	Code          string
	Name          string
	Description   string
	Restrictions  string
	Prerequisites []string
	Units         int32
	LevelNumber   pgtype.Int4
}

func (q *Queries) UpsertScrapeCourse(ctx context.Context, arg UpsertScrapeCourseParams) error {
	_, err := q.db.Exec(ctx, upsertScrapeCourse,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Restrictions,
		arg.Prerequisites,
		arg.Units,
		arg.LevelNumber,
	)
	return err
}

const upsertScrapeProgram = `-- name: UpsertScrapeProgram :one
WITH updated AS (
  UPDATE program
  SET source_url = $1,
      requirement_codes = $2,
      requirements_by_level = $3
  WHERE program.name = $4
  RETURNING id
),
inserted AS (
  INSERT INTO program (name, source_url, requirement_codes, requirements_by_level)
  SELECT $4,
         $1,
         $2,
         $3
  WHERE NOT EXISTS (SELECT 1 FROM updated)
  RETURNING id
)
SELECT id FROM updated
UNION ALL
SELECT id FROM inserted
LIMIT 1
`

type UpsertScrapeProgramParams struct {
	SourceUrl           pgtype.Text
	RequirementCodes    []string
	RequirementsByLevel []byte
	ProgramName         string
}

func (q *Queries) UpsertScrapeProgram(ctx context.Context, arg UpsertScrapeProgramParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertScrapeProgram,
		arg.SourceUrl,
		arg.RequirementCodes,
		arg.RequirementsByLevel,
		arg.ProgramName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertScrapeTeacher = `-- name: UpsertScrapeTeacher :exec
INSERT INTO teacher (name, avg_rating, avg_difficulty, department, rmp_id, num_ratings)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (rmp_id) DO UPDATE SET
  name = EXCLUDED.name,
  avg_rating = EXCLUDED.avg_rating,
  avg_difficulty = EXCLUDED.avg_difficulty,
  department = EXCLUDED.department,
  num_ratings = EXCLUDED.num_ratings
`

type UpsertScrapeTeacherParams struct {
	Name          string
	AvgRating     pgtype.Numeric
	AvgDifficulty pgtype.Numeric
	Department    string
	RmpID         string
	NumRatings    int32
}

func (q *Queries) UpsertScrapeTeacher(ctx context.Context, arg UpsertScrapeTeacherParams) error {
	_, err := q.db.Exec(ctx, upsertScrapeTeacher,
		arg.Name,
		arg.AvgRating,
		arg.AvgDifficulty,
		arg.Department,
		arg.RmpID,
		arg.NumRatings,
	)
	return err
}
