// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email)
VALUES ($1)
RETURNING id, email, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserDetails = `-- name: CreateUserDetails :one
INSERT INTO user_details (
    wake_up_time,
    bedtime,
    user_id,
    program_id,
    year,
    job_info,
    lat,
    lng,
    future_plans,
    professor_quality,
    teaching_style,
    completed
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, true)
RETURNING user_id
`

type CreateUserDetailsParams struct {
	WakeUpTime       pgtype.Time
	Bedtime          pgtype.Time
	UserID           uuid.UUID
	ProgramID        pgtype.Int8
	Year             int16
	JobInfo          string
	Lat              pgtype.Float8
	Lng              pgtype.Float8
	FuturePlans      string
	ProfessorQuality int16
	TeachingStyle    int16
}

func (q *Queries) CreateUserDetails(ctx context.Context, arg CreateUserDetailsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUserDetails,
		arg.WakeUpTime,
		arg.Bedtime,
		arg.UserID,
		arg.ProgramID,
		arg.Year,
		arg.JobInfo,
		arg.Lat,
		arg.Lng,
		arg.FuturePlans,
		arg.ProfessorQuality,
		arg.TeachingStyle,
	)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDetailsByID = `-- name: GetUserDetailsByID :one
SELECT user_id, year, job_info, future_plans, professor_quality, teaching_style, created_at, updated_at, completed, wake_up_time, bedtime, program_id, lat, lng
FROM user_details
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserDetailsByID(ctx context.Context, id uuid.UUID) (UserDetail, error) {
	row := q.db.QueryRow(ctx, getUserDetailsByID, id)
	var i UserDetail
	err := row.Scan(
		&i.UserID,
		&i.Year,
		&i.JobInfo,
		&i.FuturePlans,
		&i.ProfessorQuality,
		&i.TeachingStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Completed,
		&i.WakeUpTime,
		&i.Bedtime,
		&i.ProgramID,
		&i.Lat,
		&i.Lng,
	)
	return i, err
}

const getUserProgramID = `-- name: GetUserProgramID :one
SELECT ud.program_id as codes
FROM user_details AS ud
WHERE ud.user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProgramID(ctx context.Context, id uuid.UUID) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getUserProgramID, id)
	var codes pgtype.Int8
	err := row.Scan(&codes)
	return codes, err
}

const getUserProgramRequirements = `-- name: GetUserProgramRequirements :one
SELECT p.requirement_codes as codes
FROM user_details AS ud
JOIN program p
  ON p.id = ud.program_id
WHERE ud.user_id = $1
LIMIT 1
`

func (q *Queries) GetUserProgramRequirements(ctx context.Context, id uuid.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getUserProgramRequirements, id)
	var codes []string
	err := row.Scan(&codes)
	return codes, err
}

const hasCompletedOnboarding = `-- name: HasCompletedOnboarding :one
SELECT EXISTS(SELECT 1 FROM user_details WHERE user_id = $1 AND completed = true)::boolean
`

func (q *Queries) HasCompletedOnboarding(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasCompletedOnboarding, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
