// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email)
VALUES ($1)
RETURNING id, email, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserDetails = `-- name: CreateUserDetails :one
INSERT INTO user_details (
    wake_up_time,
    bedtime,
    user_id,
    program_id,
    year,
    job_info,
    home_address,
    future_plans,
    professor_quality,
    teaching_style,
    completed
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, true)
RETURNING user_id
`

type CreateUserDetailsParams struct {
	WakeUpTime       pgtype.Time
	Bedtime          pgtype.Time
	UserID           uuid.UUID
	ProgramID        pgtype.Int8
	Year             int16
	JobInfo          string
	HomeAddress      string
	FuturePlans      string
	ProfessorQuality int16
	TeachingStyle    int16
}

func (q *Queries) CreateUserDetails(ctx context.Context, arg CreateUserDetailsParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUserDetails,
		arg.WakeUpTime,
		arg.Bedtime,
		arg.UserID,
		arg.ProgramID,
		arg.Year,
		arg.JobInfo,
		arg.HomeAddress,
		arg.FuturePlans,
		arg.ProfessorQuality,
		arg.TeachingStyle,
	)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasCompletedOnboarding = `-- name: HasCompletedOnboarding :one
SELECT COALESCE((SELECT completed FROM user_details WHERE user_id = $1), false)::boolean
`

func (q *Queries) HasCompletedOnboarding(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasCompletedOnboarding, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
