name: CI

on:
  push:
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  server-build:
    name: Server build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: server/go.mod
          cache-dependency-path: server/go.sum

      - name: Build API
        run: go build -o /dev/null ./cmd/api

  server-lint:
    name: Server lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: server/go.mod
          cache-dependency-path: server/go.sum

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v9.2.1
        with:
          working-directory: server

  client-eslint:
    name: Client ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2.2.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: ESLint
        run: bunx eslint .

  client-build:
    name: Client build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2.2.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
        env:
          PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.PUBLIC_MAPBOX_ACCESS_TOKEN }}
